sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration':
            stripe:
                template: 'stripe.html.twig'
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration':
            stripe:
                template: 'stripe.html.twig'
